# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2020-01-14 20:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='book',
            name='author',
        ),
        migrations.RemoveField(
            model_name='book',
            name='book_type',
        ),
        migrations.RemoveField(
            model_name='book',
            name='pages',
        ),
        migrations.RemoveField(
            model_name='book',
            name='publication_date',
        ),
        migrations.RemoveField(
            model_name='book',
            name='title',
        ),
        migrations.AddField(
            model_name='book',
            name='category',
            field=models.CharField(choices=[('Books', 'Books'), ('Movies', 'Movies')], default='0000000', max_length=250),
        ),
        migrations.AddField(
            model_name='book',
            name='name',
            field=models.CharField(default='', max_length=50),
        ),
    ]
